languages:
- code: EN
  name: English
- code: RU
  name: Russian

exchanges:
  barong: barong.events.system
  peatio: peatio.events.model

keychain:
  barong:
    algorithm: RS256
    value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4dkhHRzBCWUZUQmo5bFF6MVBkbwo5UWNXTnd4UW9lbnRncUthK1dBN3BFQmwzZFpxOTVFZXhzN3VNSU1icGg5RjhiQXZvYlMyK0xWRVMrSlNtbWwrCjlnNStHQVFaQlQvbmk3V3dCRXJDS2kyQVNuQTR0enN3NW03dnMxYTIxUzJXVFFlNWFIc1EycFJrWVdMU09TVEcKc1NlRC9mc3pMNW5kSHJBOXNrWnJqNGs4MkhpYzJUWWZtbUhXWmNWT0xPUHVGRzR4eTcvVFFVNDdkcTh3L1FGSQpZaFJseUJJZEdveE1JY2paS1hqTVpnK29tS1FCQXFEa0t0ZW9Ndkt1dU9PQUhZOHVDa0FnVzlxWEpDMnB2ZTRWCjhuUk02V0pWd1hnVlpSNVo5RWZORUhWOHJYSHpSTjA4RDJLVlgwUkxjVStOQVpqaWJQTUNFZFpIdzkyRFV3WWgKUndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

  peatio:
    algorithm: RS256
    value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4dkhHRzBCWUZUQmo5bFF6MVBkbwo5UWNXTnd4UW9lbnRncUthK1dBN3BFQmwzZFpxOTVFZXhzN3VNSU1icGg5RjhiQXZvYlMyK0xWRVMrSlNtbWwrCjlnNStHQVFaQlQvbmk3V3dCRXJDS2kyQVNuQTR0enN3NW03dnMxYTIxUzJXVFFlNWFIc1EycFJrWVdMU09TVEcKc1NlRC9mc3pMNW5kSHJBOXNrWnJqNGs4MkhpYzJUWWZtbUhXWmNWT0xPUHVGRzR4eTcvVFFVNDdkcTh3L1FGSQpZaFJseUJJZEdveE1JY2paS1hqTVpnK29tS1FCQXFEa0t0ZW9Ndkt1dU9PQUhZOHVDa0FnVzlxWEpDMnB2ZTRWCjhuUk02V0pWd1hnVlpSNVo5RWZORUhWOHJYSHpSTjA4RDJLVlgwUkxjVStOQVpqaWJQTUNFZFpIdzkyRFV3WWgKUndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

events:
- name: Email Confirmation
  key: user.email.confirmation.token
  exchange: barong
  templates:
    EN:
      subject: Registration Confirmation
      template_path: templates/email_confirmation.en.tpl
    RU:
      subject: Подтверждение Регистрации
      template_path: templates/email_confirmation.ru.tpl

- name: Password Reset
  key: user.password.reset.token
  exchange: barong
  templates:
    EN:
      subject: Password Reset
      template_path: templates/password_reset.en.tpl
    RU:
      subject: Сброс Пароля
      template_path: templates/password_reset.ru.tpl

- name: Deposit Accepted
  key: deposit.updated
  exchange: peatio
  expression: changes.state == "submitted" && record.state == "accepted"
  templates:
    EN:
      subject: Deposit Accepted
      template_path: templates/deposit_accepted.en.tpl

- name: Withdrawal Succeed
  key: withdraw.updated
  exchange: peatio
  expression: changes.state in ["errored", "confirming"] && record.state == "succeed"
  templates:
    EN:
      subject: Withdrawal Succeed
      template_path: templates/withdraw_succeed.en.tpl

- name: New Beneficiary
  key: beneficiary.created
  exchange: peatio
  templates:
    EN:
      subject: New Beneficiary
      template_path: templates/new_beneficiary.en.tpl
