languages:
- code: EN
  name: English
- code: RU
  name: Russian

keychain:
  barong_system:
    algorithm: RS256
    value: "changeme"

  barong_model:
    algorithm: RS256
    value: "changeme"

  peatio:
    algorithm: RS256
    value: "changeme"

exchanges:
  barong_system: barong.events.system
  barong_model: barong.events.model
  peatio: peatio.events.model

events:
- name: Email Confirmation
  key: user.email.confirmation.token
  exchange: barong_system
  templates:
    EN:
      subject: Registration Confirmation
      template_path: templates/en/email_confirmation.tpl
    RU:
      subject: Подтверждение Регистрации
      template_path: templates/ru/email_confirmation.tpl

- name: Password Reset
  key: user.password.reset.token
  exchange: barong_system
  templates:
    EN:
      subject: Password Reset
      template_path: templates/en/password_reset.tpl
    RU:
      subject: Сброс Пароля
      template_path: templates/ru/password_reset.tpl

- name: Session Create
  key: session.create
  exchange: barong_system
  templates:
    EN:
      subject: New Login
      template_path: templates/en/session_create.tpl

- name: User Level Upgrade
  key: user.updated
  exchange: barong_model
  expression: changes.level != nil && record.level > changes.level
  templates:
    EN:
      subject:
      template_path: templates/en/user_level_upgrade.tpl

- name: Deposit Accepted
  key: deposit.updated
  exchange: peatio
  expression: changes.state == "submitted" && record.state == "accepted"
  templates:
    EN:
      subject: Deposit Accepted
      template_path: templates/en/deposit_accepted.tpl

- name: Withdrawal Succeed
  key: withdraw.updated
  exchange: peatio
  expression: changes.state in ["errored", "confirming"] && record.state == "succeed"
  templates:
    EN:
      subject: Withdrawal Succeed
      template_path: templates/en/withdraw_succeed.tpl

- name: New Beneficiary
  key: beneficiary.created
  exchange: peatio
  templates:
    EN:
      subject: New Beneficiary
      template_path: templates/en/new_beneficiary.tpl
